(setq org-capture-templates
        '(("t" "TODO" entry (file "~/.emacs.d/org/agenda.org")
        "* TODO %? \n  %U" :empty-lines 0)
        ("s" "Scheduled TODO" entry (file "~/.emacs.d/org/agenda.org")
        "* TODO %?  \nSCHEDULED: %^t\n  %U" :empty-lines 1)
        ("d" "Deadline" entry (file "~/.emacs.d/org/agenda.org")
            "* TODO %? \n  DEADLINE: %^t" :empty-lines 1)
        ("p" "Priority" entry (file+datetree "~/.emacs.d/org/agenda.org")
        "* TODO [#A] %? \n  SCHEDULED: %^t")
        ("a" "Appointment" entry (file "~/.emacs.d/org/agenda.org")
        "* %? \n  %^t")
        ("l" "Link" entry (file "~/.emacs.d/org/agenda.org")
        "* TODO %a %? \nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n")
        ("n" "Note" entry (file+datetree "~/.emacs.d/org/agenda.org")
            "* %? \n%U" :empty-lines 0)
        ("j" "Journal" entry (file+datetree "~/.emacs.d/org/agenda.org")
         "* %? %^G\nEntered on %U\n")
        ("T" "amm TODO" entry (file "~/.emacs.d/org/amm.org")
        "* TODO %? \n  %U" :empty-lines 0)
        ("S" "amm Scheduled TODO" entry (file "~/.emacs.d/org/amm.org")
        "* TODO %?  \nSCHEDULED: %^t\n  %U" :empty-lines 1)
        ("D" "amm Deadline" entry (file "~/.emacs.d/org/amm.org")
            "* TODO %? \n  DEADLINE: %^t" :empty-lines 1)
        ("P" "amm Priority" entry (file+datetree "~/.emacs.d/org/amm.org")
        "* TODO [#A] %? \n  SCHEDULED: %^t")
        ("A" "amm Appointment" entry (file "~/.emacs.d/org/amm.org")
        "* %? \n  %^t")
        ("L" "amm Link" entry (file "~/.emacs.d/org/amm.org")
        "* TODO %a %? \nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n")
        ("N" "amm Note" entry (file+datetree "~/.emacs.d/org/notes.org")
            "* %? \n%U" :empty-lines 0)
        ("J" "amm Journal" entry (file+datetree "~/.emacs.d/org/amm.org")
         "* %? %^G\nEntered on %U\n")))
